# Generated by Django 2.1.1 on 2018-10-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_node'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
    ]
